services:
  config-server:
    build:
      context: ./config-server
      dockerfile: ./Dockerfile
    env_file:
      - .env
    container_name: ${CONFIG_SERVER_CONTAINER_NAME}
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl --fail --silent http://localhost:${CONFIG_SERVER_PORT}/actuator/health | grep 'UP'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - microservices-net

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: ./Dockerfile
    env_file:
      - .env
    container_name: ${EUREKA_SERVER_CONTAINER_NAME}
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl --fail --silent http://localhost:${EUREKA_SERVER_PORT}/actuator/health | grep 'UP'" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - microservices-net
    depends_on:
      config-server:
        condition: service_healthy

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: ./Dockerfile
    env_file:
      - .env
    container_name: ${GATEWAY_SERVICE_CONTAINER_NAME}
    ports:
      - "${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}"
    environment:
      - TZ=Europe/Moscow
    networks:
      - microservices-net
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "sh -c", "curl --fail --silent http://localhost:${GATEWAY_SERVER_PORT}/actuator/health | grep 'UP'" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  user_db:
    image: postgres
    env_file:
      - .env
    container_name: ${USERDB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_USER_NAME}
    volumes:
      - pg_data_user:/var/lib/postgresql/data
    ports:
      - "${POSTGRESDB_USER_PORT}:${POSTGRESDB_DOCKER_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRESDB_USER} -d ${POSTGRESDB_USER_NAME}'" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - microservices-net
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    env_file:
      - .env
    container_name: ${USER_SERVICE_CONTAINER_NAME}
    ports:
      - "${USER_SERVER_PORT}:${USER_SERVER_PORT}"
    networks:
      - microservices-net
    depends_on:
      gateway-server:
        condition: service_started
      user_db:
        condition: service_healthy
#      kafka:
#        condition: service_healthy
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl --fail --silent http://localhost:${USER_SERVER_PORT}/actuator/health | grep 'UP'" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  exchange_db:
    image: postgres
    env_file:
      - .env
    container_name: ${EXCHANGEDB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_EXCHANGE_NAME}
    volumes:
      - pg_data_exchange:/var/lib/postgresql/data
    ports:
      - "${POSTGRESDB_EXCHANGE_PORT}:${POSTGRESDB_DOCKER_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRESDB_USER} -d ${POSTGRESDB_EXCHANGE_NAME}'" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - microservices-net
    restart: unless-stopped

  exchange-service:
    build:
      context: ./exchange-service
      dockerfile: ./Dockerfile
    env_file:
      - .env
    container_name: ${EXCHANGE_SERVICE_CONTAINER_NAME}
    ports:
      - "${EXCHANGE_SERVER_PORT}:${EXCHANGE_SERVER_PORT}"
    networks:
      - microservices-net
    depends_on:
      gateway-server:
        condition: service_healthy
      exchange_db:
        condition: service_healthy
#      kafka:
#        condition: service_healthy
#      kibana:
#        condition: service_started
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl --fail --silent http://localhost:${EXCHANGE_SERVER_PORT}/actuator/health | grep 'UP'" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  book_db:
    image: postgres
    env_file:
      - .env
    container_name: ${BOOKDB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_BOOK_NAME}
    volumes:
      - pg_data_book:/var/lib/postgresql/data
    ports:
      - "${POSTGRESDB_BOOK_PORT}:${POSTGRESDB_DOCKER_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRESDB_USER} -d ${POSTGRESDB_BOOK_NAME}'" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - microservices-net
    restart: unless-stopped

  book-service:
    build:
      context: ./book-service
      dockerfile: ./Dockerfile
    env_file:
      - .env
    container_name: ${BOOK_SERVICE_CONTAINER_NAME}
    ports:
      - "${BOOK_SERVER_PORT}:${BOOK_SERVER_PORT}"
    networks:
      - microservices-net
    depends_on:
      gateway-server:
        condition: service_started
      book_db:
        condition: service_healthy
#      kafka:
#        condition: service_healthy
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl --fail --silent http://localhost:${BOOK_SERVER_PORT}/actuator/health | grep 'UP'" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  keycloak_db:
    image: postgres
    env_file:
      - .env
    container_name: ${KEYCLOAKDB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER_KEYCLOAK}
      POSTGRES_PASSWORD: ${POSTGRESDB_PASSWORD_KEYCLOAK}
      POSTGRES_DB: ${POSTGRESDB_KEYCLOAK_NAME}
    volumes:
      - pg_data_keycloak:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRESDB_USER_KEYCLOAK} -d ${POSTGRESDB_KEYCLOAK_NAME}'" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - microservices-net
    restart: unless-stopped

  keycloak-server:
    image: quay.io/keycloak/keycloak
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    ports:
      - 8080:8080
    env_file:
      - .env
#    volumes:
#      - ./realm-export-with-roles.json:/opt/keycloak/data/import/msa-order-ticket-payment.json
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      TZ: "Europe/Moscow"
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${POSTGRESDB_USER_KEYCLOAK}
      KC_DB_PASSWORD: ${POSTGRESDB_PASSWORD_KEYCLOAK}
      KC_DB_URL: jdbc:postgresql://${KEYCLOAKDB_CONTAINER_NAME}:5432/${POSTGRESDB_KEYCLOAK_NAME}
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    networks:
      microservices-net:
        aliases:
          - ${KEYCLOAK_HOST_NAME}
    command:
      - "start-dev"
#      - "--import-realm"

networks:
  microservices-net:
    driver: bridge

volumes:
  pg_data_exchange:
  pg_data_book:
  pg_data_user:
  pg_data_keycloak: