eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_CONTAINER_NAME}:${EUREKA_SERVER_PORT}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, refresh

spring:
  cloud:
    config:
      overrideSystemProperties: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: ${OIDC_ISSUER_URI_OUTER}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_CLIENT_NAME}
